### ISSUE TITLE
dub imports

### ISSUE THREAD

**Issue by 9il** [DlangApache/kfkaConsumer#1]
kfkaConsumer should use packages from code.dlang.org

``` json
{
    ...
    "dependencies": {
        "zookeeper": "~>0.1.0",
        "librdkafka": "~>0.1.0"
    }
}
```

**Comment by dushibaiyu** [comment]
how can i set path in json?
like this : 
 "dependencies": {
        "zookeeper": "~>0.1.0",
        "librdkafka": "~>0.1.0"
    },

```
"librdkafka" : {
        "path": "librdkafka"
    }, 
    "zookeeper": {
        "path": "zookeeper"
    }
```

?

**Comment by dushibaiyu** [comment]
fixed. and i want to know, dub will seach in github?why i don't Submitted to code.dlang.org, why dub will find librdkafka?

**Comment by 9il** [comment]
> fixed. and i want to know, dub will seach in github?why i don't Submitted to code.dlang.org, why dub will find librdkafka?

I submitted librdkafka and zookeeper

**Comment by dushibaiyu** [comment]
Great, Thanks.
